[2024-05-18T20:59:28.047+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T20:59:28.065+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-18T20:59:22.352393+00:00 [queued]>
[2024-05-18T20:59:28.073+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-18T20:59:22.352393+00:00 [queued]>
[2024-05-18T20:59:28.074+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-18T20:59:28.088+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2024-05-18 20:59:22.352393+00:00
[2024-05-18T20:59:28.102+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T20:59:28.104+0000] {standard_task_runner.py:63} INFO - Started process 73 to run task
[2024-05-18T20:59:28.104+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'manual__2024-05-18T20:59:22.352393+00:00', '--job-id', '369', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmp5qicxz0l']
[2024-05-18T20:59:28.107+0000] {standard_task_runner.py:91} INFO - Job 369: Subtask upload_file
[2024-05-18T20:59:28.146+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file manual__2024-05-18T20:59:22.352393+00:00 [running]> on host f358725b4696
[2024-05-18T20:59:28.237+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T20:59:22.352393+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T20:59:22.352393+00:00'
[2024-05-18T20:59:28.239+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T20:59:28.247+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-18T20:59:28.249+0000] {base.py:84} INFO - Using connection ID 'googlecloud' for task execution.
[2024-05-18T20:59:28.250+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T20:59:28.251+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 98, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: ./data_example.txt
[2024-05-18T20:59:28.259+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_loader, task_id=upload_file, run_id=manual__2024-05-18T20:59:22.352393+00:00, execution_date=20240518T205922, start_date=20240518T205928, end_date=20240518T205928
[2024-05-18T20:59:28.272+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 369 for task upload_file (./data_example.txt; 73)
[2024-05-18T20:59:28.319+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T20:59:28.338+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T20:59:28.340+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
