[2024-05-18T21:07:21.012+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T21:07:21.029+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-18T21:07:18.073433+00:00 [queued]>
[2024-05-18T21:07:21.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-18T21:07:18.073433+00:00 [queued]>
[2024-05-18T21:07:21.038+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-18T21:07:21.053+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2024-05-18 21:07:18.073433+00:00
[2024-05-18T21:07:21.061+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=111) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T21:07:21.062+0000] {standard_task_runner.py:63} INFO - Started process 113 to run task
[2024-05-18T21:07:21.062+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'manual__2024-05-18T21:07:18.073433+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmp83js4cjo']
[2024-05-18T21:07:21.064+0000] {standard_task_runner.py:91} INFO - Job 374: Subtask upload_file
[2024-05-18T21:07:21.110+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file manual__2024-05-18T21:07:18.073433+00:00 [running]> on host a464b827924a
[2024-05-18T21:07:21.188+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T21:07:18.073433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T21:07:18.073433+00:00'
[2024-05-18T21:07:21.191+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T21:07:21.198+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-18T21:07:21.200+0000] {base.py:84} INFO - Using connection ID 'googlecloud' for task execution.
[2024-05-18T21:07:21.201+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T21:07:21.202+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 98, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: opt/***/raw/sales/22-08-09/file.json
[2024-05-18T21:07:21.213+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_loader, task_id=upload_file, run_id=manual__2024-05-18T21:07:18.073433+00:00, execution_date=20240518T210718, start_date=20240518T210721, end_date=20240518T210721
[2024-05-18T21:07:21.227+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 374 for task upload_file (opt/***/raw/sales/22-08-09/file.json; 113)
[2024-05-18T21:07:21.237+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T21:07:21.255+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T21:07:21.257+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
