[2024-05-18T20:24:53.938+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T20:24:53.952+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-18T20:19:01.641651+00:00 [queued]>
[2024-05-18T20:24:53.958+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-18T20:19:01.641651+00:00 [queued]>
[2024-05-18T20:24:53.958+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-05-18T20:24:53.971+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2024-05-18 20:19:01.641651+00:00
[2024-05-18T20:24:53.978+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2339) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T20:24:53.979+0000] {standard_task_runner.py:63} INFO - Started process 2341 to run task
[2024-05-18T20:24:53.979+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'manual__2024-05-18T20:19:01.641651+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmp5uh6rnle']
[2024-05-18T20:24:53.981+0000] {standard_task_runner.py:91} INFO - Job 362: Subtask upload_file
[2024-05-18T20:24:54.018+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file manual__2024-05-18T20:19:01.641651+00:00 [running]> on host b5cbc22da81e
[2024-05-18T20:24:54.075+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T20:19:01.641651+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T20:19:01.641651+00:00'
[2024-05-18T20:24:54.077+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T20:24:54.083+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-18T20:24:54.084+0000] {base.py:84} INFO - Using connection ID 'googlecloud' for task execution.
[2024-05-18T20:24:54.085+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T20:24:54.086+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 98, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: .\data_example.txt
[2024-05-18T20:24:54.092+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_loader, task_id=upload_file, run_id=manual__2024-05-18T20:19:01.641651+00:00, execution_date=20240518T201901, start_date=20240518T202453, end_date=20240518T202454
[2024-05-18T20:24:54.102+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 362 for task upload_file (.\data_example.txt; 2341)
[2024-05-18T20:24:54.114+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T20:24:54.133+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T20:24:54.136+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
