[2024-05-18T19:45:23.631+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T19:45:23.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-18T19:44:57.107321+00:00 [queued]>
[2024-05-18T19:45:23.656+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-18T19:44:57.107321+00:00 [queued]>
[2024-05-18T19:45:23.657+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-18T19:45:23.669+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2024-05-18 19:44:57.107321+00:00
[2024-05-18T19:45:23.679+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1756) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T19:45:23.681+0000] {standard_task_runner.py:63} INFO - Started process 1758 to run task
[2024-05-18T19:45:23.681+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'manual__2024-05-18T19:44:57.107321+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmp1yc__7nu']
[2024-05-18T19:45:23.684+0000] {standard_task_runner.py:91} INFO - Job 340: Subtask upload_file
[2024-05-18T19:45:23.723+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file manual__2024-05-18T19:44:57.107321+00:00 [running]> on host b5cbc22da81e
[2024-05-18T19:45:23.785+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T19:44:57.107321+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T19:44:57.107321+00:00'
[2024-05-18T19:45:23.787+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T19:45:23.793+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-18T19:45:23.794+0000] {base.py:84} INFO - Using connection ID 'google-cloud-default' for task execution.
[2024-05-18T19:45:23.795+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T19:45:23.796+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 98, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: 2024-05-18/data.txt
[2024-05-18T19:45:23.802+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_loader, task_id=upload_file, run_id=manual__2024-05-18T19:44:57.107321+00:00, execution_date=20240518T194457, start_date=20240518T194523, end_date=20240518T194523
[2024-05-18T19:45:23.810+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 340 for task upload_file (2024-05-18/data.txt; 1758)
[2024-05-18T19:45:23.856+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T19:45:23.883+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T19:45:23.885+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
