[2024-05-19T12:24:41.770+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T12:24:41.783+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-19T12:24:39.670452+00:00 [queued]>
[2024-05-19T12:24:41.790+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_loader.upload_file manual__2024-05-19T12:24:39.670452+00:00 [queued]>
[2024-05-19T12:24:41.790+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T12:24:41.802+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2024-05-19 12:24:39.670452+00:00
[2024-05-19T12:24:41.808+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1232) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T12:24:41.809+0000] {standard_task_runner.py:63} INFO - Started process 1236 to run task
[2024-05-19T12:24:41.809+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_loader', 'upload_file', 'manual__2024-05-19T12:24:39.670452+00:00', '--job-id', '388', '--raw', '--subdir', 'DAGS_FOLDER/data_loader.py', '--cfg-path', '/tmp/tmpfj97rgxi']
[2024-05-19T12:24:41.812+0000] {standard_task_runner.py:91} INFO - Job 388: Subtask upload_file
[2024-05-19T12:24:41.849+0000] {task_command.py:426} INFO - Running <TaskInstance: data_loader.upload_file manual__2024-05-19T12:24:39.670452+00:00 [running]> on host a464b827924a
[2024-05-19T12:24:41.888+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/context.py:212: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-19T12:24:41.912+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_loader' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T12:24:39.670452+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T12:24:39.670452+00:00'
[2024-05-19T12:24:41.914+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T12:24:41.920+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-19T12:24:41.922+0000] {base.py:84} INFO - Using connection ID 'googlecloud' for task execution.
[2024-05-19T12:24:41.926+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T12:24:41.927+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 98, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /opt/***/stg/sales/2024-05-19/file.avro
[2024-05-19T12:24:41.934+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_loader, task_id=upload_file, run_id=manual__2024-05-19T12:24:39.670452+00:00, execution_date=20240519T122439, start_date=20240519T122441, end_date=20240519T122441
[2024-05-19T12:24:41.945+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 388 for task upload_file (/opt/***/stg/sales/2024-05-19/file.avro; 1236)
[2024-05-19T12:24:41.983+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T12:24:42.002+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T12:24:42.005+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
